create table if not exists public.early_access_submissions (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) <= 254),
  organization_role text check (organization_role is null or char_length(organization_role) <= 200),
  created_at timestamptz not null default now()
);

alter table public.early_access_submissions enable row level security;